### ISSUE TITLE
additional properties

### ISSUE THREAD

**Issue by thob** [typora-community-plugin/typora-plugin-front-matter#1]
it would be fantastic if one could add additional properties like `title`, `description`, `slug`, `stylesheet`, `image` automatically (optional of course)

**Comment by plylrnsdy** [comment]
just insert property's key?

**Comment by thob** [comment]
I mean automatically, as a reminder, like a template :-)

**Comment by plylrnsdy** [comment]
ok, I see

**Comment by plylrnsdy** [comment]
the newest version 1.2.1 is released. you can update it in plugin marketplace

**Comment by thob** [comment]
it's working as expected, fantastic. as a further extension I could imagine that you could provide a way to pre-populate the value with for instance the image or stylesheet url or author name. This would make it easier to maintain …

_PS: I need to define the properties for each vault/directory separately, is this intended? No, global settings available?_

**Comment by plylrnsdy** [comment]
> it's working as expected, fantastic. as a further extension I could image that you could provide a way to pre-populate the value with for instance the image or stylesheet url or author name. This would make it easier to maintain …

I think your need a templater. You can discuss about it at [#23](https://github.com/typora-community-plugin/typora-community-plugin/issues/23)

> PS: I need to define the properties for each vault/directory separately, is this intended? No, global settings available?

It only support vault's settings now. You can discuss about global settings at [#22](https://github.com/typora-community-plugin/typora-community-plugin/issues/22)

You can copy folder `.typora` under vault for sharing same settings between different vaults.
