### ISSUE TITLE
点击任意级别标题后，会触发updated

### ISSUE THREAD

**Issue by at2008** [typora-community-plugin/typora-plugin-front-matter#2]
点击任意级别标题，然后切换到其他标题后，会触发updated；我这边在typora中启用了 即时渲染

![image](https://github.com/user-attachments/assets/1cebd42a-100b-41e7-a78f-0a691fe2fbeb)

**Comment by plylrnsdy** [comment]
Typora 是这样实现的 (点击标题后导致文档变为已编辑状态)，和插件没关系

**Comment by at2008** [comment]
感谢回复！
